### ISSUE TITLE
Add documentation for inotify limit errors

### ISSUE THREAD

**Issue by joydeep-b** [ut-amrl/config-reader#3]
It is quite common to hit inotify limits on Ubuntu. When that happens, the config-reader inotify watch will fail, with an error like:
```
ERROR: Couldn't add watch to the file: config/f1_config.lua
Reason: No space left on device
``` 
We need to add documentation for how to circumvent this by either ignoring, or raising the limit.
See, for example: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by TheCynosure** [comment]
Can we close this, I think this documentation was added.
